GET http://kfin-project.onrender.com/employees

###

GET https://kfin-project.onrender.com/employees/64bd75a9a264b3112f6e5df6

###

POST https://kfin-project.onrender.com/employees
Content-Type: application/json

{
    "name": "aikagra",
    "email": "aik@xyz.co.",
    "mobileNo": 9850500276
}

###

DELETE http://127.0.0.1/employees/64bd77c0a264b3112f6e5e00